### ISSUE TITLE
kubecost-cost-model container not starting up in Azure when deployed with OpenCost Helm chart.

### ISSUE THREAD

**Issue by ckarwicki** [opencost/opencost-helm-chart#73] opened 2023-05-22 15:09 UTC
Hi,

It appears `kubecost-cost-model` container is not starting up when deployed in Azure AKS with Opencost Helm chart. There are no errors in logs, even changing `LOG_LEVEL` to `debug` didn't have any effect (probably because container doesn't even start). We suspect there is something with the OpenCost Helm chart incorrectly configuring deployment of  `kubecost-cost-model`.  Tried many things but no difference, same log Info and container not started:
1. Helm chart 1.14.0, regular `quay.io/kubecost1/kubecost-cost-model:prod-1.103.1` and with `gcr.io/kubecost1/opencost:kc-eu-2023`
2. Helm chart 1.14.3,  regular `quay.io/kubecost1/kubecost-cost-model:prod-1.103.1` and with `gcr.io/kubecost1/opencost:kc-eu-2023`
3. With Service Principal secret and without.

Details:
Azure AKS v1.25.6
Deployed with ArgoCD v2.6.7+5bcd846
```
project: ska
source:
  repoURL: 'https://opencost.github.io/opencost-helm-chart'
  targetRevision: 1.14.3
  helm:
    values: |
      extraVolumes:
      - name: service-key-secret
        secret:
          secretName: azure-service-key
      opencost:
        exporter:
          extraEnv:
            LOG_LEVEL: debug
          extraVolumeMounts:
          - mountPath: /var/secrets
            name: service-key-secret
        prometheus:
          internal:
            enabled: true
            namespaceName: monitoring
            port: 9090
            serviceName: prometheus-kube-prometheus-prometheus
        ui:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              ingress.kubernetes.io/ssl-redirect: "true"
              kubernetes.io/tls-acme: "true"
              nginx.ingress.kubernetes.io/modsecurity-snippet: |
                SecRuleEngine On
            ingressClassName: nginx
    version: v3
  chart: opencost
destination:
  server: 'https://kubernetes.default.svc'
  namespace: kubecost
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  retry:
    limit: 5
```
Logs, only this is in logs no matter what is changed:
```
27
2023-05-22T15:06:16.509888074Z ??? Log level set to debug
26
2023-05-22T15:06:16.510069775Z INF Starting cost-model version 1.103.1 (6dd98b305de3b1d1c826a041cf36a2db4d267ee1)
25
2023-05-22T15:06:16.510244777Z INF Prometheus/Thanos Client Max Concurrency set to 5
24
2023-05-22T15:06:16.520338258Z INF Success: retrieved the 'up' query against prometheus at: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
23
2023-05-22T15:06:16.535087077Z INF Retrieved a prometheus config file from: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
22
2023-05-22T15:06:16.560877685Z INF Using scrape interval of 60.000000
21
2023-05-22T15:06:16.561828193Z INF NAMESPACE: kubecost
20
2023-05-22T15:06:16.764493528Z INF Done waiting
19
2023-05-22T15:06:16.76481283Z INF Starting *v1.Deployment controller
18
2023-05-22T15:06:16.764965632Z INF Starting *v1.Namespace controller
17
2023-05-22T15:06:16.765258734Z INF Starting *v1.Node controller
16
2023-05-22T15:06:16.765370835Z INF Starting *v1.Pod controller
15
2023-05-22T15:06:16.765829738Z INF Starting *v1.StatefulSet controller
14
2023-05-22T15:06:16.765492036Z INF Starting *v1.Service controller
13
2023-05-22T15:06:16.765945539Z INF Starting *v1.ConfigMap controller
12
2023-05-22T15:06:16.76597254Z INF Starting *v1.DaemonSet controller
11
2023-05-22T15:06:16.76599914Z INF Starting *v1.Job controller
10
2023-05-22T15:06:16.76604564Z INF Starting *v1.ReplicaSet controller
9
2023-05-22T15:06:16.76606434Z INF Starting *v1.PersistentVolume controller
8
2023-05-22T15:06:16.766082241Z INF Starting *v1.PersistentVolumeClaim controller
7
2023-05-22T15:06:16.766104141Z INF Starting *v1.StorageClass controller
6
2023-05-22T15:06:16.766124241Z INF Starting *v1.ReplicationController controller
5
2023-05-22T15:06:16.766142541Z INF Starting *v1beta1.PodDisruptionBudget controller
4
2023-05-22T15:06:16.767947656Z INF Found ProviderID starting with "azure", using Azure Provider
3
2023-05-22T15:06:16.771786287Z INF No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found
2
2023-05-22T15:06:16.775200814Z INF No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
1
2023-05-22T15:06:16.777853635Z INF Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'
```

`kubectl describe pod -n kubecost`

```
Name:             opencost-ff69d5985-9l9w4
Namespace:        kubecost
Priority:         0
Service Account:  opencost
Node:             aks-agentpool-40542563-vmss000003/10.224.0.4
Start Time:       Sun, 21 May 2023 18:00:35 -0400
Labels:           app.kubernetes.io/instance=opencost
                  app.kubernetes.io/name=opencost
                  pod-template-hash=ff69d5985
Annotations:      <none>
Status:           Running
IP:               10.244.0.12
IPs:
  IP:           10.244.0.12
Controlled By:  ReplicaSet/opencost-ff69d5985
Containers:
  opencost:
    Container ID:   containerd://8c9a36212c3056cbd40986bc66312109d01a89ffe1d8d5baadcec985f9759c6c
    Image:          quay.io/kubecost1/kubecost-cost-model:prod-1.103.1
    Image ID:       quay.io/kubecost1/kubecost-cost-model@sha256:2993835c1090048431f667d8e4c8bb59e561bd90c6e431f548a692a8a6a6dbe1
    Port:           9003/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 22 May 2023 11:13:29 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 22 May 2023 11:06:16 -0400
      Finished:     Mon, 22 May 2023 11:08:16 -0400
    Ready:          False
    Restart Count:  231
    Limits:
      cpu:     999m
      memory:  1Gi
    Requests:
      cpu:      10m
      memory:   55Mi
    Liveness:   http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=10
    Readiness:  http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=200
    Environment:
      PROMETHEUS_SERVER_ENDPOINT:  http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      CLUSTER_ID:                  default-cluster
      LOG_LEVEL:                   debug
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9lxpz (ro)
      /var/secrets from service-key-secret (rw)
  opencost-ui:
    Container ID:   containerd://a896d239f89cff03b9286e86cbf1178bcd8cf5bb19914bf1e7f4bd1a87646dd7
    Image:          quay.io/kubecost1/opencost-ui:prod-1.103.1
    Image ID:       quay.io/kubecost1/opencost-ui@sha256:526415266a674bc108d4a71284fbe04342ccbbfb3089313cb1e1421a4b218128
    Port:           9090/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 21 May 2023 18:00:37 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     999m
      memory:  1Gi
    Requests:
      cpu:        10m
      memory:     55Mi
    Liveness:     http-get http://:9090/healthz delay=30s timeout=1s period=10s #success=1 #failure=10
    Readiness:    http-get http://:9090/healthz delay=30s timeout=1s period=10s #success=1 #failure=10
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9lxpz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  service-key-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  azure-service-key
    Optional:    false
  kube-api-access-9lxpz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  33m (x2700 over 17h)    kubelet  Readiness probe failed: Get "http://10.244.0.12:9003/healthz": dial tcp 10.244.0.12:9003: connect: connection refused
  Warning  Unhealthy  8m38s (x2297 over 17h)  kubelet  Liveness probe failed: Get "http://10.244.0.12:9003/healthz": dial tcp 10.244.0.12:9003: connect: connection refused
  Warning  BackOff    3m39s (x2689 over 16h)  kubelet  Back-off restarting failed container
```

Could anyone help with following:
1. Is Azure AKS officially supported in OpenCost Helm chart?
2. How to configure OpenCost for Azure AKS or at least how to troubleshoot it?

Any help would be highly appreciated.

**Comment by mattray** [comment] 2023-05-23 03:53
OpenCost definitely works and is supported on AKS, I'm not sure what the issue is. No need to use the `kc-eu-2023` containers, those are pre-1.103. I'll ask around and see if there are some debugging suggestions.

**Comment by mattray** [comment] 2023-05-23 04:02
A few suggestions from Kubecost Support:

Network Policies: Make sure that there's nothing blocking network communication to and from the pod. AKS has network policies that can prevent pods from communicating with each other, and this might be preventing the cost-model pod from accessing its necessary services.

Azure Firewall: Also, ensure there aren't any firewall rules on Azure that are blocking the necessary traffic for the cost-model pod.

Azure CNI: Azure AKS offers two networking options: Kubenet and Azure CNI. If you're using Azure CNI, check if there's an IP shortage issue as it could prevent new pods from establishing network connectivity.

Resource Constraints: Check if there are enough CPU and memory resources in your node for the cost-model pod. It might be being killed due to insufficient resources, though this is less likely given your current limits and requests.

Can exec into pod, etc, check logs, maybe try disabling the liveness and readiness probes temporarily to see if the pod stays up also; not the long term solution but will help with debugging.

**Comment by ckarwicki** [comment] 2023-05-24 01:26
Thanks @mattray for the reply. I checked networking policies, firewall rules already - this is test cluster with no restrictions. We are also using Kubnet instead of CNI. Also, tried to increase delay for liveness and readiness probes but no difference.

I am able to exec into `kubecost-cost-model` container itself before it gets shut down. Seems `kubecost-cost-model` container is listening on port 9090 instead of 9003 ? :
```
/ $ netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN
tcp        0      0 10.244.1.45:51862       10.0.0.1:443            ESTABLISHED
tcp        0      0 10.244.1.45:49700       169.254.169.254:80      ESTABLISHED
tcp        0      0 10.244.1.45:49680       169.254.169.254:80      TIME_WAIT
tcp        0      0 10.244.1.45:55522       10.0.6.217:9090         ESTABLISHED
tcp        0      0 10.244.1.45:49686       169.254.169.254:80      TIME_WAIT
tcp        0      0 :::80                   :::*                    LISTEN
tcp        0      0 :::9090                 :::*                    LISTEN
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  3      [ ]         STREAM     CONNECTED     51791089
unix  3      [ ]         STREAM     CONNECTED     51791092
unix  3      [ ]         STREAM     CONNECTED     51791090
unix  3      [ ]         STREAM     CONNECTED     51791091
/ $ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      -
tcp        0      0 :::80                   :::*                    LISTEN      -
tcp        0      0 :::9090                 :::*                    LISTEN      -
/ $ command terminated with exit code 137
```
Do you know where can I find logs of the `kubecost-cost-model` container or some other useful information?

**Comment by ckarwicki** [comment] 2023-05-30 19:08
Hi @mattray,

Was able to pinpoint the issue. It appears that following needs to be explicitly provided when deploying with Helm chart:
```
opencost:
  exporter:
    extraEnv:
      CONFIG_PATH: /var/configs/
```
Not sure why it is causing the issue or whether the price data OpenCost is showing is accurate but it fixes the error and `kubecost-cost-model` container is running now. It appears there are many other environment variables that are not provided for `kubecost-cost-model` in OpenCost Helm while there are in the original deployment KubeCost `cost-analyzer`. Not sure why that would be different since it appears it is the same app.

**Comment by kitforbes** [comment] 2023-08-15 15:38
I had a similar issue with the `opencost` Helm Chart from https://opencost.github.io/opencost-helm-chart
In my case, disabling the liveness probe allowed the container to stay alive long enough to get beyond the ratecard log entry.

**Comment by mattray** [comment] 2023-08-28 07:24
If someone wants to test and open a PR to enable configuring the liveness probe we'd get it merged.

**Comment by TheisFerre** [comment] 2023-08-30 12:47
I have experienced the same issue when using AKS. 

As mentioned by @kitforbes the problem was solved by increasing value of `initialDelaySeconds`. When increasing it to `90`, i still experienced two failures from the `livenessProbe` before the container started. However, it ended up working since the `failureThreshold` is set to `3`.

I have submitted a pr #112 where `initialDelaySeconds` is set to `120` to be on the safe side. With this i did not get any failures from any of the probes.

**Comment by mattray** [comment] 2023-08-31 04:26
I've merged https://github.com/opencost/opencost-helm-chart/pull/112, so I'm closing this issue.

**Closed by mattray** 2023-08-31 04:26 UTC
Labels: enhancement, good first issue, help wanted

**Comment by waynewong-ascenda** [comment] 2023-11-02 09:31
I experienced the same problem with latest version
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m27s                  default-scheduler  Successfully assigned devops/opencost-868f85955d-zhfxl to ip-10-27-1-252.ap-southeast-1.compute.internal
  Normal   Created    2m42s (x2 over 4m22s)  kubelet            Created container opencost
  Normal   Started    2m41s (x2 over 4m22s)  kubelet            Started container opencost
  Normal   Pulled     57s (x3 over 4m22s)    kubelet            Container image "gcr.io/kubecost1/opencost:latest" already present on machine
  Warning  Unhealthy  57s (x10 over 3m16s)   kubelet            Readiness probe failed: Get "http://10.27.1.4:9003/healthz": dial tcp 10.27.1.4:9003: connect: connection refused
  Warning  Unhealthy  57s (x6 over 3m12s)    kubelet            Liveness probe failed: Get "http://10.27.1.4:9003/healthz": dial tcp 10.27.1.4:9003: connect: connection refused
  Normal   Killing    57s (x2 over 2m42s)    kubelet            Container opencost failed liveness probe, will be restarted
```
